version: "3.5"
services:
  scoparella_app:
    container_name: scoparella_api
    build: "../../../../"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - "LOG_LEVEL=info"
      - "TEST=1"
      - "HOST=0.0.0.0"
      - "DB_HOST=scoparella_db"
      - "DB_PORT=1433"
    networks:
      - scoparella_net
    hostname: scoparellaapp.local

networks:
  scoparella_net:
    external: true
    name: scoparella_net
