apiVersion: v1
kind: Service
metadata:
  name: "scoparella-api-service"
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: scoparella-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
