apiVersion: v1
kind: Service
metadata:
  name: "scoparella-api-service"
spec:
  type: LoadBalancer
  selector:
    app: scoparella-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
