apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: $IDENTITY_NAME
spec:
  containers:
    - name: demo
      image: mcr.microsoft.com/k8s/aad-pod-identity/demo:1.2
      args:
        - --subscriptionid=009e0a99-8c4c-49fb-8efb-e79bdaeb58d0
        - --clientid=$IDENTITY_CLIENT_ID
        - --resourcegroup=$RESOURCE_GROUP
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
