version: "3.5"
services:
  scoparella-db:
    container_name: scoparella_db
    image: microsoft/mssql-server-linux:latest
    ports:
      - "1440:1433"
    expose:
      - "1440"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@ss55w0rd"
    volumes:
      - .:/start
    command:
      - /start/mssql.setup.sh
    networks:
      - scoparella_net

networks:
  scoparella_net:
    external: false
    name: scoparella_net
